# Generated by Django 4.1.4 on 2022-12-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('out for delivery', 'out for devlivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
